export const CartActionTypes = {
    TOGGLE_CART_HIDDEN: "TOGGLE_CART_HIDDEN",
    ADD_ITEM: "ADD_ITEM",
    CLAER_ITEM_FROM_CART: "CLAER_ITEM_FROM_CART",
    REMOVE_ITEM: "REMOVE_ITEM",
    CLEAR_ENTIRE_CART: "CLEAR_ENTIRE_CART"
}

export default CartActionTypes;
